
const a = document.createElement("div");
document.body.prepend(a);
a.setAttribute("class","container");
a.setAttribute("id","firscon");
var b = document.querySelector(".container");
const c = document.createElement("div")
b.append(c);
c.setAttribute("class","row border-top");
c.setAttribute("id","firstrow");
var d = document.querySelector("#firstrow");
const e = document.createElement("div");
d.append(e);
e.setAttribute("class","col");
var d = document.querySelector("#firstrow");
const f = document.createElement("div");
d.append(f);
f.setAttribute("class","col");
f.setAttribute("id","picture");
var d = document.querySelector("#firstrow");
const g = document.createElement("div");
d.append(g);
g.setAttribute("class","col")
var d  = document.querySelector("#picture");
const h = document.createElement("br");
const i = document.createElement("img");
d.append(h);
d.append(i);
i.setAttribute("src","Chandan.jpg");
i.setAttribute("class","rounded-circle mx-auto d-block border border-warning");
i.setAttribute("width","160px");
i.setAttribute("height","160px");
var d  = document.querySelector("#picture");
const j = document.createElement("br");
d.append(j);
var b = document.querySelector(".container");
var k = document.createElement("p");
b.append(k);
var k =  document.createElement("div");
b.append(k);
k.setAttribute("class","container");
k.setAttribute("id","seccon");
var b = document.querySelector("#seccon");
var k = document.createElement("h1")
b.append(k);
k.setAttribute("class","text-center");
k.setAttribute("id","h1name");
var b = document.querySelector("#h1name");
var k = document.createElement("span");
b.append(k);
k.innerText = " CHANDAN ";
k.setAttribute("id","name");
var b = document.querySelector("#firscon");
var k = document.createElement("div")
b.append(k);
k.setAttribute("class","row");
k.setAttribute("id","subfirrow");
var b = document.querySelector("#subfirrow");
var k = document.createElement("br");
b.append(k);
var b = document.querySelector("#firscon");
var k = document.createElement("p");
b.append(k);
k.setAttribute("class","text-center border-bottom");
k.innerText="15-1-40 P.B Road, VIZIANAGARAM 535002 | 9940107129 | chandanpentapati@gmail.com | www.cpmac.in";
var b = document.querySelector("#firscon");
var k = document.createElement("div");
b.append(k);
k.setAttribute("class","row");
k.setAttribute("id","secrow");
var b = document.querySelector("#secrow");
var k = document.createElement("div");
b.append(k);
k.setAttribute("class","col-6 border-right");
k.setAttribute("id","srcol1")
var b = document.querySelector("#secrow");
var k = document.createElement("div");
b.append(k);
k.setAttribute("class","col-6 border-left");
k.setAttribute("id","srcol2")
var b = document.querySelector("#srcol1");
var k = document.createElement("div");
b.append(k);
k.setAttribute("class","row")
k.setAttribute("id","ssecrow1");
var b = document.querySelector("#ssecrow1");
var k = document.createElement("div");
b.append(k);
k.setAttribute("class","row")
k.setAttribute("id","sssecrow1");
var b = document.querySelector("#sssecrow1");
var k = document.createElement("div");
b.append(k);
k.setAttribute("class","col-3");
k.setAttribute("id","ssseccol");
var b = document.querySelector("#ssseccol");
var k = document.createElement("i");
b.append(k);
k.setAttribute("class","fas fa-user");
k.setAttribute("aria-hidden","true");
k.setAttribute("style","color:gold");
var b = document.querySelector("#sssecrow1");
var k = document.createElement("div");
b.append(k);
k.setAttribute("class","col");
k.setAttribute("id","ssseccol1");
var b = document.querySelector("#ssseccol1");
var k = document.createElement("h3");
b.append(k);
k.innerText="Profile";
var b = document.querySelector("#ssecrow1");
var k = document.createElement("div");
b.append(k);
k.setAttribute("class","row");
k.setAttribute("id","sssecrow2");
var b = document.querySelector("#sssecrow2");
var k = document.createElement("div");
b.append(k);
k.setAttribute("class","container");
k.setAttribute("id","intro");
var b = document.querySelector("#intro");
var k = document.createElement("p");
b.append(k);
k.innerText="Innovative optimized solution seeker.Excited to be at the development phase of my new career as a web developer. I am ambitious, adventurous,assidious, animated, and an alliteration";
var b = document.querySelector("#srcol1");
var k = document.createElement("div");
b.append(k);
k.setAttribute("class","row");
k.setAttribute("id","ssecrow2");
var b = document.querySelector("#ssecrow2");
var k = document.createElement("div");
b.append(k);
k.setAttribute("class","row");
k.setAttribute("id","sssrow21");
var b = document.querySelector("#sssrow21");
var k = document.createElement("div");
b.append(k);
k.setAttribute("class","col-3");
k.setAttribute("id","sssr2col");
var b = document.querySelector("#sssr2col")
var k = document.createElement("i");
b.append(k);
k.setAttribute("class","fas fa-flask");
k.setAttribute("aria-hidden","true");
k.setAttribute("style","color:gold");
var b = document.querySelector("#sssrow21");
var k = document.createElement("div");
b.append(k);
k.setAttribute("class","col-9");
k.setAttribute("id","sssr2col1");
var b = document.querySelector("#sssr2col1");
var k = document.createElement("h3");
b.append(k);
k.innerText="SKILLS"
var b = document.querySelector("#ssecrow2");
var k = document.createElement("div");
b.append(k);
k.setAttribute("class","row");
var b = document.querySelector("#srcol1");
var k = document.createElement("div");
b.append(k);
k.setAttribute("class","container");
k.setAttribute("id","TSC");
var b = document.querySelector("#TSC");
var k = document.createElement("div");
b.append(k);
k.setAttribute("class","row");
k.setAttribute("id","TSCR1");
var b = document.querySelector("#TSCR1");
var k = document.createElement("h6");
b.append(k);
k.setAttribute("class","text-center");
k.innerText ="Technical Skills";
var b = document.querySelector("#TSC");
var k = document.createElement("div");
b.append(k);
k.setAttribute("class","row");
k.setAttribute("id","TSCR2");
var b = document.querySelector("#TSCR2");
var k = document.createElement("div");
b.append(k);
k.setAttribute("class","col");
k.innerText="HTML";
var b = document.querySelector("#TSCR2");
var k = document.createElement("div");
b.append(k);
k.setAttribute("class","col");
var b = document.querySelector("#TSCR2");
var k = document.createElement("div");
b.append(k);
k.setAttribute("class","col");
k.setAttribute("id",id="TSCR2R");
var b = document.querySelector("#TSCR2R");
var k = document.createElement("input");
b.append(k);
k.setAttribute("class","range-all");
k.setAttribute("type","range");
var b = document.querySelector("#TSC");
var k = document.createElement("div");
b.append(k);
k.setAttribute("class","row");
k.setAttribute("id","TSCR3");
var b = document.querySelector("#TSCR3");
var k = document.createElement("div");
b.append(k);
k.setAttribute("class","col");
k.innerText="CSS";
var b = document.querySelector("#TSCR3");
var k = document.createElement("div");
b.append(k);
k.setAttribute("class","col");
var b = document.querySelector("#TSCR3");
var k = document.createElement("div");
b.append(k);
k.setAttribute("class","col");
k.setAttribute("id",id="TSCR3R");
var b = document.querySelector("#TSCR3R");
var k = document.createElement("input");
b.append(k);
k.setAttribute("class","range-all");
k.setAttribute("type","range");
var b = document.querySelector("#TSC");
var k = document.createElement("div");
b.append(k);
k.setAttribute("class","row");
k.setAttribute("id","TSCR4");
var b = document.querySelector("#TSCR4");
var k = document.createElement("div");
b.append(k);
k.setAttribute("class","col");
k.innerText="JS";
var b = document.querySelector("#TSCR4");
var k = document.createElement("div");
b.append(k);
k.setAttribute("class","col");
var b = document.querySelector("#TSCR4");
var k = document.createElement("div");
b.append(k);
k.setAttribute("class","col");
k.setAttribute("id",id="TSCR4R");
var b = document.querySelector("#TSCR4R");
var k = document.createElement("input");
b.append(k);
k.setAttribute("class","range-all");
k.setAttribute("type","range");
var b = document.querySelector("#TSC");
var k = document.createElement("div");
b.append(k);
k.setAttribute("class","row");
k.setAttribute("id","TSCR5");
var b = document.querySelector("#TSCR5");
var k = document.createElement("div");
b.append(k);
k.setAttribute("class","col");
k.innerText="BootStrap";
var b = document.querySelector("#TSCR5");
var k = document.createElement("div");
b.append(k);
k.setAttribute("class","col");
var b = document.querySelector("#TSCR5");
var k = document.createElement("div");
b.append(k);
k.setAttribute("class","col");
k.setAttribute("id",id="TSCR5R");
var b = document.querySelector("#TSCR5R");
var k = document.createElement("input");
b.append(k);
k.setAttribute("class","range-all");
k.setAttribute("type","range");
var b = document.querySelector("#TSC");
var k = document.createElement("div");
b.append(k);
k.setAttribute("class","row");
k.setAttribute("id","TSCR6");
var b = document.querySelector("#TSCR6");
var k = document.createElement("div");
b.append(k);
k.setAttribute("class","col");
k.innerText="PYTHON";
var b = document.querySelector("#TSCR6");
var k = document.createElement("div");
b.append(k);
k.setAttribute("class","col");
var b = document.querySelector("#TSCR6");
var k = document.createElement("div");
b.append(k);
k.setAttribute("class","col");
k.setAttribute("id",id="TSCR6R");
var b = document.querySelector("#TSCR6R");
var k = document.createElement("input");
b.append(k);
k.setAttribute("class","range-all");
k.setAttribute("type","range");
var b = document.querySelector("#TSC");
var k = document.createElement("div");
b.append(k);
k.setAttribute("class","row");
k.setAttribute("id","TSCR7");
var b = document.querySelector("#TSCR7");
var k = document.createElement("div");
b.append(k);
k.setAttribute("class","col");
k.innerText="C#";
var b = document.querySelector("#TSCR7");
var k = document.createElement("div");
b.append(k);
k.setAttribute("class","col");
var b = document.querySelector("#TSCR7");
var k = document.createElement("div");
b.append(k);
k.setAttribute("class","col");
k.setAttribute("id",id="TSCR7R");
var b = document.querySelector("#TSCR7R");
var k = document.createElement("input");
b.append(k);
k.setAttribute("class","range-all");
k.setAttribute("type","range");
var b = document.querySelector("#TSC");
var k = document.createElement("div");
b.append(k);
k.setAttribute("class","row");
k.setAttribute("id","TSCR8");
var b = document.querySelector("#TSCR8");
var k = document.createElement("h6");
b.append(k);
k.setAttribute("class","text-center");
k.innerText ="Additional Skills";
var b = document.querySelector("#TSC");
var k = document.createElement("div");
b.append(k);
k.setAttribute("class","row");
k.setAttribute("id","TSCR9");
var b = document.querySelector("#TSCR9");
var k = document.createElement("div");
b.append(k);
k.setAttribute("class","col");
k.innerText="ProjectManagement";
var b = document.querySelector("#TSCR9");
var k = document.createElement("div");
b.append(k);
k.setAttribute("class","col");
var b = document.querySelector("#TSCR9");
var k = document.createElement("div");
b.append(k);
k.setAttribute("class","col");
k.setAttribute("id",id="TSCR9R");
var b = document.querySelector("#TSCR9R");
var k = document.createElement("input");
b.append(k);
k.setAttribute("class","range-all");
k.setAttribute("type","range");
var b = document.querySelector("#TSC");
var k = document.createElement("div");
b.append(k);
k.setAttribute("class","row");
k.setAttribute("id","TSCR10");
var b = document.querySelector("#TSCR10");
var k = document.createElement("div");
b.append(k);
k.setAttribute("class","col");
k.innerText="Recuitment";
var b = document.querySelector("#TSCR10");
var k = document.createElement("div");
b.append(k);
k.setAttribute("class","col");
var b = document.querySelector("#TSCR10");
var k = document.createElement("div");
b.append(k);
k.setAttribute("class","col");
k.setAttribute("id",id="TSCR10R");
var b = document.querySelector("#TSCR10R");
var k = document.createElement("input");
b.append(k);
k.setAttribute("class","range-all");
k.setAttribute("type","range");
var b = document.querySelector("#TSC");
var k = document.createElement("div");
b.append(k);
k.setAttribute("class","row");
k.setAttribute("id","TSCR11");
var b = document.querySelector("#TSCR11");
var k = document.createElement("div");
b.append(k);
k.setAttribute("class","col");
k.innerText="Editing";
var b = document.querySelector("#TSCR11");
var k = document.createElement("div");
b.append(k);
k.setAttribute("class","col");
var b = document.querySelector("#TSCR11");
var k = document.createElement("div");
b.append(k);
k.setAttribute("class","col");
k.setAttribute("id",id="TSCR11R");
var b = document.querySelector("#TSCR11R");
var k = document.createElement("input");
b.append(k);
k.setAttribute("class","range-all");
k.setAttribute("type","range");
var b = document.querySelector("#TSC");
var k = document.createElement("div");
b.append(k);
k.setAttribute("class","row");
k.setAttribute("id","TSCR12");
var b = document.querySelector("#TSCR12");
var k = document.createElement("div");
b.append(k);
k.setAttribute("class","col");
k.innerText="FundRaising";
var b = document.querySelector("#TSCR12");
var k = document.createElement("div");
b.append(k);
k.setAttribute("class","col");
var b = document.querySelector("#TSCR12");
var k = document.createElement("div");
b.append(k);
k.setAttribute("class","col");
k.setAttribute("id",id="TSCR12R");
var b = document.querySelector("#TSCR12R");
var k = document.createElement("input");
b.append(k);
k.setAttribute("class","range-all");
k.setAttribute("type","range");
var b = document.querySelector("#TSC");
var k = document.createElement("div");
b.append(k);
k.setAttribute("class","row");
k.setAttribute("id","TSCR13");
var b = document.querySelector("#TSCR13");
var k = document.createElement("div");
b.append(k);
k.setAttribute("class","col");
k.innerText="BusinessDevelopment";
var b = document.querySelector("#TSCR13");
var k = document.createElement("div");
b.append(k);
k.setAttribute("class","col");
var b = document.querySelector("#TSCR13");
var k = document.createElement("div");
b.append(k);
k.setAttribute("class","col");
k.setAttribute("id",id="TSCR13R");
var b = document.querySelector("#TSCR13R");
var k = document.createElement("input");
b.append(k);
k.setAttribute("class","range-all");
k.setAttribute("type","range");
var b = document.querySelector("#srcol1");
var k = document.createElement("div");
b.append(k);
k.setAttribute("class","row");
k.setAttribute("id","WER");
var b = document.querySelector("#WER");
var k = document.createElement("div");
b.append(k);
k.setAttribute("class","row");
k.setAttribute("id","WERSR");
var b = document.querySelector("#WERSR");
var k = document.createElement("div");
b.append(k);
k.setAttribute("class","col-2");
k.setAttribute("id","WERSRC");
var b = document.querySelector("#WERSR");
var k = document.createElement("div");
b.append(k);
k.setAttribute("class","col-10");
k.setAttribute("id","WERSRC1");
var b = document.querySelector("#WERSRC");
var k = document.createElement("i");
b.append(k);
k.setAttribute("class","fas fa-briefcase");
k.setAttribute("aria-hidden","true");
k.setAttribute("style","color:gold");
var b = document.querySelector("#WERSRC1");
var k = document.createElement("h3");
b.append(k);
k.innerText="WORK EXPERIENCE"
var b = document.querySelector("#WER");
var k = document.createElement("div");
b.append(k);
k.setAttribute("class","row");
var b = document.querySelector("#srcol1");
var k = document.createElement("div");
b.append(k);
k.setAttribute("class","container");
k.setAttribute("id","WERSRC2")
var b = document.querySelector("#WERSRC2");
var k = document.createElement("div");
b.append(k);
k.setAttribute("class","row");
k.setAttribute("id","WERSRCR2");
var b = document.querySelector("#WERSRCR2");
var k = document.createElement("div");
b.append(k);
k.setAttribute("class","col");
k.setAttribute("id","WERSRCRC1");
var b = document.querySelector("#WERSRCRC1");
var k = document.createElement("h6");
b.append(k);
k.innerText="DEVELOPER";
var b =document.querySelector("#WERSRCR2");
var k = document.createElement("div");
b.append(k);
k.setAttribute("class","col");
k.setAttribute("id","WERSRCRC2");
var b =document.querySelector("#WERSRCRC2");
var k = document.createElement("span");
b.append(k);
k.innerText="01/2019 - Present";
var b = document.querySelector("#WERSRC2");
var k = document.createElement("div");
b.append(k);
k.setAttribute("class","row");
k.setAttribute("id","PAT1");
var b = document.querySelector("#PAT1");
var k = document.createElement("div");
b.append(k);
k.setAttribute("class","container");
k.setAttribute("id","PAT1C");
var b = document.querySelector("#PAT1C");
var k = document.createElement("p");
b.append(k);
k.innerText="PROGRAMMER ANALYST TRAINEE";
var b = document.querySelector("#PAT1C");
var k = document.createElement("ul");
b.append(k);
k.setAttribute("id","PATUL");
var b = document.querySelector("#PATUL");
var k = document.createElement("li");
b.append(k);
k.innerText="Currently Working as an RPA DEVELOPER";
var b = document.querySelector("#PATUL");
var k = document.createElement("li");
b.append(k);
k.innerText="i have developed around 4 bots which helped the client in cost reduction reduce human work force ";
var b = document.querySelector("#PATUL");
var k = document.createElement("li");
b.append(k);
k.innerText="i have knowledge on c,c++,c#,python,Javascript,html,css,bootstrap<br> and RPA Tool Automation Anywhere";
var b = document.querySelector("#srcol2");
var k = document.createElement("div");
b.append(k);
k.setAttribute("class","row");
k.setAttribute("id","LWER");
var b = document.querySelector("#LWER");
var k = document.createElement("div");
b.append(k);
k.setAttribute("class","row");
k.setAttribute("id","LWERR");
var b = document.querySelector("#LWERR");
var k = document.createElement("div");
b.append(k);
k.setAttribute("class","col-2");
k.setAttribute("id","LWERRC");
var b = document.querySelector("#LWERRC");
var k = document.createElement("i");
b.append(k);
k.setAttribute("class","fas fa-briefcase");
k.setAttribute("style","color:gold");
k.setAttribute("aria-hidden","true");
var b = document.querySelector("#LWERR");
var k = document.createElement("div");
b.append(k);
k.setAttribute("class","col-10");
k.setAttribute("id","LWERRC1");
var b = document.querySelector("#LWERRC1");
var k = document.createElement("h3");
b.append(k);
k.innerText="WORK EXPERIENCE";
var b = document.querySelector("#srcol2");
var k = document.createElement("div");
b.append(k);
k.setAttribute("class","container");
k.setAttribute("id","CONLWE");
var b = document.querySelector("#CONLWE");
var k = document.createElement("div");
b.append(k);
k.setAttribute("class","row");
k.setAttribute("id","CONLWER");
var b = document.querySelector("#CONLWER");
var k = document.createElement("div");
b.append(k);
k.setAttribute("class","col");
k.setAttribute("id","CONLWERC");
var b = document.querySelector("#CONLWERC");
var k = document.createElement("h6");
b.append(k);
k.innerText="DEVELOPER";
var b = document.querySelector("#CONLWER");
var k = document.createElement("div");
b.append(k);
k.setAttribute("class","col");
k.setAttribute("id","CONLWERC1");
var b = document.querySelector("#CONLWERC1");
var k = document.createElement("span");
b.append(k);
k.innerText="01/2019 - Present";
var b = document.querySelector("#CONLWE");
var k = document.createElement("div");
b.append(k);
k.setAttribute("class","col");
k.setAttribute("id","CONLWER1");
var b = document.querySelector("#CONLWER1");
var k = document.createElement("div")
b.append(k);
k.setAttribute("class","container");
k.setAttribute("id","CONLWEC");
var b = document.querySelector("#CONLWEC");
var k = document.createElement("p");
b.append(k);
k.innerText="PROGRAMMER ANALYST TRAINEE";
var b = document.querySelector("#CONLWEC");
var k = document.createElement("ul");
b.append(k);
k.setAttribute("id","LWEUL");
var b = document.querySelector("#LWEUL");
var k = document.createElement("li");
b.append(k);
k.innerText="Currently Working as an RPA DEVELOPER ";
var b = document.querySelector("#LWEUL");
var k = document.createElement("li");
b.append(k);
k.innerText="i have developed around 4 bots which helped the client in cost reduction reduce human work force ";
var b = document.querySelector("#LWEUL");
var k = document.createElement("li");
b.append(k);
k.innerText="i have knowledge on c,c++,c#,python,Javascript,html,css,bootstrap<br> and RPA Tool Automation Anywhere";
var b = document.querySelector("#srcol2");
var k = document.createElement("div");
b.append(k);
k.setAttribute("class","row");
k.setAttribute("id","EDU");
var b = document.querySelector("#EDU");
var k = document.createElement("div");
b.append(k);
k.setAttribute("class","row");
k.setAttribute("id","EDUR");
var b = document.querySelector("#EDUR");
var k = document.createElement("div");
b.append(k);
k.setAttribute("class","col-3");
k.setAttribute("id","EDURC");
var b = document.querySelector("#EDURC");
var k = document.createElement("i");
b.append(k);
k.setAttribute("class","fas fa-graduation-cap");
k.setAttribute("aria-hidden","true");
k.setAttribute("style","color:gold");
var b = document.querySelector("#EDUR");
var k = document.createElement("div");
b.append(k);
k.setAttribute("class","col-9");
k.setAttribute("id","EDURC1");
var b = document.querySelector("#EDURC1");
var k = document.createElement("h3");
b.append(k);
k.innerText="EDUCATION";
var b =document.querySelector("#EDU");
var k = document.createElement("div");
b.append(k);
k.setAttribute("class","row");
var b = document.querySelector("#srcol2");
var k = document.createElement("div");
b.append(k);
k.setAttribute("class","container");
k.setAttribute("id","FC");
var b =document.querySelector("#FC");
var k = document.createElement("div");
b.append(k);
k.setAttribute("class","row");
k.setAttribute("id","FCR");
var b =document.querySelector("#FCR");
var k = document.createElement("div");
b.append(k);
k.setAttribute("class","col-9");
k.setAttribute("id","FCRC");
var b =document.querySelector("#FCR");
var k = document.createElement("div");
b.append(k);
k.setAttribute("class","col-3");
k.innerText="2015-2019";
k.setAttribute("id","FCRC1");
var b =document.querySelector("#FCRC");
var k = document.createElement("h6");
b.append(k);
k.innerText="Bachelor of Engineering in Computer Science Engineering";
var b = document.querySelector("#FC");
var k = document.createElement("div");
b.append(k);
k.setAttribute("class","row");
k.setAttribute("id","FCR1");
var b =document.querySelector("#FCR1");
var k = document.createElement("p");
b.append(k);
k.innerText="SATHYABAMA INSTITUTE OF SCIENCE AND TECHNOLOGY, CHENNAI, TAMILNADU";
var b =document.querySelector("#FCR1");
var k = document.createElement("ul");
b.append(k);
k.setAttribute("id","FCR1UL");
var b =document.querySelector("#FCR1UL");
var k = document.createElement("li");
b.append(k);
k.innerText="CGPA: 7.41";
k.setAttribute("id","FC");
var b =document.querySelector("#FC");
var k = document.createElement("div");
b.append(k);
k.setAttribute("class","row");
k.setAttribute("id","FCR2");
var b =document.querySelector("#FCR2");
var k = document.createElement("div");
b.append(k);
k.setAttribute("class","col-9");
k.setAttribute("id","FCR2C");
var b =document.querySelector("#FCR2");
var k = document.createElement("div");
b.append(k);
k.setAttribute("class","col-3");
k.innerText="2013-2015";
k.setAttribute("id","FCR2C1");
var b =document.querySelector("#FCR2C");
var k = document.createElement("h6");
b.append(k);
k.innerText="XII";
var b = document.querySelector("#FC");
var k = document.createElement("div");
b.append(k);
k.setAttribute("class","row");
k.setAttribute("id","FCR3");
var b =document.querySelector("#FCR3");
var k = document.createElement("p");
b.append(k);
k.innerText="ASCENT JUNIOR COLLEGE, VISAKHAPATNAM, ANDHRA PRADESH";
var b =document.querySelector("#FCR3");
var k = document.createElement("ul");
b.append(k);
k.setAttribute("id","FCR3UL");
var b =document.querySelector("#FCR3UL");
var k = document.createElement("li");
b.append(k);
k.innerText="PERCENTAGE: 67.8";
k.setAttribute("id","FC");
var b =document.querySelector("#FC");
var k = document.createElement("div");
b.append(k);
k.setAttribute("class","row");
k.setAttribute("id","FCR4");
var b =document.querySelector("#FCR4");
var k = document.createElement("div");
b.append(k);
k.setAttribute("class","col-9");
k.setAttribute("id","FCR4C");
var b =document.querySelector("#FCR4");
var k = document.createElement("div");
b.append(k);
k.setAttribute("class","col-3");
k.innerText="2012-2013";
k.setAttribute("id","FCR4C1");
var b =document.querySelector("#FCR4C");
var k = document.createElement("h6");
b.append(k);
k.innerText="X"; 

var b = document.querySelector("#FC");
var k = document.createElement("div");
b.append(k);
k.setAttribute("class","row");
k.setAttribute("id","FCR5");
var b =document.querySelector("#FCR5");
var k = document.createElement("p");
b.append(k);
k.innerText="THE SUN SCHOOL, VIZIANAGARAM, ANDHRA PRADESH";

var b = document.querySelector("#FC");
var k = document.createElement("div");
b.append(k);
k.setAttribute("class","row");
k.setAttribute("id","FCR6");
var b =document.querySelector("#FCR6");
var k = document.createElement("ul");
b.append(k);
k.setAttribute("id","FCR6UL");
var b =document.querySelector("#FCR6UL");
var k = document.createElement("li");
b.append(k);
k.innerText="CGPA: 7.8";







