const a = document.createElement("div");
document.body.prepend(a);
a.setAttribute("class","main");
var b = document.querySelector(".main");
var k = document.createElement("div");
b.append(k);
k.classList.add("container");
var b = document.querySelector(".container");
var k = document.createElement("div");
b.append(k);
k.classList.add("row");
k.classList.add("justify-content-md-center");
k.setAttribute("id","heading");
var b = document.querySelector("#heading");
var c = document.createElement("h1");
b.append(c);
c.classList.add("text-center");
c.innerText="CALCULATOR";
var b = document.querySelector(".container");
var k = document.createElement("div");
b.append(k);
k.classList.add("row");
k.classList.add("justify-content-md-center");
k.setAttribute("id","displayrow");
var b = document.querySelector("#displayrow");
var k = document.createElement("div");
b.append(k);
k.classList.add("col-md-auto");
k.setAttribute("id","displaycol1");
var b = document.querySelector("#displayrow");
var k = document.createElement("div");
b.append(k);
k.classList.add("col-md-auto");
k.setAttribute("id","displaycol2");
var b = document.querySelector("#displaycol1");
var k = document.createElement("input");
b.append(k);
k.setAttribute("type","text");
k.setAttribute("id","calciInput");
var b = document.querySelector("#displaycol2");
var k = document.createElement("button");
b.append(k);
k.classList.add("btn");
k.classList.add("btn-dark");
k.classList.add("btn-lg");
k.setAttribute("id","c");
k.innerText="C";
var b = document.querySelector(".container");
var k = document.createElement("div");
b.append(k);
k.classList.add("row");
k.classList.add("justify-content-md-center");
k.setAttribute("id","brr1");
var b = document.querySelector("#brr1");
var k = document.createElement("br");
b.append(k);
var b = document.querySelector(".container");
var k = document.createElement("div");
b.append(k);
k.classList.add("row");
k.classList.add("justify-content-md-center");
k.setAttribute("id","kr1");
var b = document.querySelector("#kr1");
var k = document.createElement("div");
b.append(k);
k.classList.add("col-md-auto");
k.setAttribute("id","kr1c1");
var b = document.querySelector("#kr1c1");
var k = document.createElement("button");
b.append(k);
k.classList.add("btn");
k.classList.add("btn-dark");
k.classList.add("btn-lg");
k.setAttribute("id","one");
k.innerText="1";
var b = document.querySelector("#kr1");
var k = document.createElement("div");
b.append(k);
k.classList.add("col-md-auto");
k.setAttribute("id","kr1c2");
var b = document.querySelector("#kr1c2");
var k = document.createElement("button");
b.append(k);
k.classList.add("btn");
k.classList.add("btn-dark");
k.classList.add("btn-lg");
k.setAttribute("id","two");
k.innerText="2";
var b = document.querySelector("#kr1");
var k = document.createElement("div");
b.append(k);
k.classList.add("col-md-auto");
k.setAttribute("id","kr1c3");
var b = document.querySelector("#kr1c3");
var k = document.createElement("button");
b.append(k);
k.classList.add("btn");
k.classList.add("btn-dark");
k.classList.add("btn-lg");
k.setAttribute("id","three");
k.innerText="3";
var b = document.querySelector("#kr1");
var k = document.createElement("div");
b.append(k);
k.classList.add("col-md-auto");
k.setAttribute("id","kr1c4");
var b = document.querySelector("#kr1c4");
var k = document.createElement("button");
b.append(k);
k.classList.add("btn");
k.classList.add("btn-dark");
k.classList.add("btn-lg");
k.setAttribute("id","plus");
k.innerText="+";
var b = document.querySelector(".container");
var k = document.createElement("div");
b.append(k);
k.classList.add("row");
k.classList.add("justify-content-md-center");
k.setAttribute("id","brr2");
var b = document.querySelector("#brr2");
var k = document.createElement("br");
b.append(k);
var b = document.querySelector(".container");
var k = document.createElement("div");
b.append(k);
k.classList.add("row");
k.classList.add("justify-content-md-center");
k.setAttribute("id","kr2");
var b = document.querySelector("#kr2");
var k = document.createElement("div");
b.append(k);
k.classList.add("col-md-auto");
k.setAttribute("id","kr2c1");
var b = document.querySelector("#kr2c1");
var k = document.createElement("button");
b.append(k);
k.classList.add("btn");
k.classList.add("btn-dark");
k.classList.add("btn-lg");
k.setAttribute("id","four");
k.innerText="4";
var b = document.querySelector("#kr2");
var k = document.createElement("div");
b.append(k);
k.classList.add("col-md-auto");
k.setAttribute("id","kr2c2");
var b = document.querySelector("#kr2c2");
var k = document.createElement("button");
b.append(k);
k.classList.add("btn");
k.classList.add("btn-dark");
k.classList.add("btn-lg");
k.setAttribute("id","five");
k.innerText="5";
var b = document.querySelector("#kr2");
var k = document.createElement("div");
b.append(k);
k.classList.add("col-md-auto");
k.setAttribute("id","kr2c3");
var b = document.querySelector("#kr2c3");
var k = document.createElement("button");
b.append(k);
k.classList.add("btn");
k.classList.add("btn-dark");
k.classList.add("btn-lg");
k.setAttribute("id","six");
k.innerText="6";
var b = document.querySelector("#kr2");
var k = document.createElement("div");
b.append(k);
k.classList.add("col-md-auto");
k.setAttribute("id","kr2c4");
var b = document.querySelector("#kr2c4");
var k = document.createElement("button");
b.append(k);
k.classList.add("btn");
k.classList.add("btn-dark");
k.classList.add("btn-lg");
k.setAttribute("id","minus");
k.innerText="-";
var b = document.querySelector(".container");
var k = document.createElement("div");
b.append(k);
k.classList.add("row");
k.classList.add("justify-content-md-center");
k.setAttribute("id","brr3");
var b = document.querySelector("#brr3");
var k = document.createElement("br");
b.append(k);
var b = document.querySelector(".container");
var k = document.createElement("div");
b.append(k);
k.classList.add("row");
k.classList.add("justify-content-md-center");
k.setAttribute("id","kr3");
var b = document.querySelector("#kr3");
var k = document.createElement("div");
b.append(k);
k.classList.add("col-md-auto");
k.setAttribute("id","kr3c1");
var b = document.querySelector("#kr3c1");
var k = document.createElement("button");
b.append(k);
k.classList.add("btn");
k.classList.add("btn-dark");
k.classList.add("btn-lg");
k.setAttribute("id","seven");
k.innerText="7";
var b = document.querySelector("#kr3");
var k = document.createElement("div");
b.append(k);
k.classList.add("col-md-auto");
k.setAttribute("id","kr3c2");
var b = document.querySelector("#kr3c2");
var k = document.createElement("button");
b.append(k);
k.classList.add("btn");
k.classList.add("btn-dark");
k.classList.add("btn-lg");
k.setAttribute("id","eight");
k.innerText="8";
var b = document.querySelector("#kr3");
var k = document.createElement("div");
b.append(k);
k.classList.add("col-md-auto");
k.setAttribute("id","kr3c3");
var b = document.querySelector("#kr3c3");
var k = document.createElement("button");
b.append(k);
k.classList.add("btn");
k.classList.add("btn-dark");
k.classList.add("btn-lg");
k.setAttribute("id","nine");
k.innerText="9";
var b = document.querySelector("#kr3");
var k = document.createElement("div");
b.append(k);
k.classList.add("col-md-auto");
k.setAttribute("id","kr3c4");
var b = document.querySelector("#kr3c4");
var k = document.createElement("button");
b.append(k);
k.classList.add("btn");
k.classList.add("btn-dark");
k.classList.add("btn-lg");
k.setAttribute("id","mul");
k.innerText="*";
var b = document.querySelector(".container");
var k = document.createElement("div");
b.append(k);
k.classList.add("row");
k.classList.add("justify-content-md-center");
k.setAttribute("id","brr4");
var b = document.querySelector("#brr4");
var k = document.createElement("br");
b.append(k);
var b = document.querySelector(".container");
var k = document.createElement("div");
b.append(k);
k.classList.add("row");
k.classList.add("justify-content-md-center");
k.setAttribute("id","kr4");
var b = document.querySelector("#kr4");
var k = document.createElement("div");
b.append(k);
k.classList.add("col-md-auto");
k.setAttribute("id","kr4c1");
var b = document.querySelector("#kr4c1");
var k = document.createElement("button");
b.append(k);
k.classList.add("btn");
k.classList.add("btn-dark");
k.classList.add("btn-lg");
k.setAttribute("id","dot");
k.innerText=".";
var b = document.querySelector("#kr4");
var k = document.createElement("div");
b.append(k);
k.classList.add("col-md-auto");
k.setAttribute("id","kr4c2");
var b = document.querySelector("#kr4c2");
var k = document.createElement("button");
b.append(k);
k.classList.add("btn");
k.classList.add("btn-dark");
k.classList.add("btn-lg");
k.setAttribute("id","zero");
k.innerText="0";
var b = document.querySelector("#kr4");
var k = document.createElement("div");
b.append(k);
k.classList.add("col-md-auto");
k.setAttribute("id","kr4c3");
var b = document.querySelector("#kr4c3");
var k = document.createElement("button");
b.append(k);
k.classList.add("btn");
k.classList.add("btn-dark");
k.classList.add("btn-lg");
k.setAttribute("id","eql");
k.innerText="=";
var b = document.querySelector("#kr4");
var k = document.createElement("div");
b.append(k);
k.classList.add("col-md-auto");
k.setAttribute("id","kr4c4");
var b = document.querySelector("#kr4c4");
var k = document.createElement("button");
b.append(k);
k.classList.add("btn");
k.classList.add("btn-dark");
k.classList.add("btn-lg");
k.setAttribute("id","div");
k.innerText="/";
var b = document.querySelector(".container");
var k = document.createElement("div");
b.append(k);
k.classList.add("row");
k.classList.add("justify-content-md-center");
k.setAttribute("id","brr5");
var b = document.querySelector("#brr5");
var k = document.createElement("br");
b.append(k);